# -*- coding: utf-8 -*-
"""Plot the error data generated by Box_error.py."""

import os

from Simulator.cases import TD_case
import Simulator.cases.DS_case_3phase as DS_case_3phase

os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'

import numpy as np
import matplotlib.pyplot as plt
import Simulator.cases.fixed_module2 as fixed_module2

from Simulator import PROJECT_ROOT


# =============================================================================
# Feasible region comparison chart
# =============================================================================

def plot_feasible_region(data_path, output_dir):
    """Read feasible region data and draw comparison graphs"""
    data = np.load(data_path)

    boundary_points = data['boundary_points']
    A_moderate = data['A_moderate']
    b_moderate = data['b_moderate']
    A_feasible = data['A_feasible']
    b_feasible = data['b_feasible']
    xlim = data['xlim']
    ylim = data['ylim']
    dtheta = data['dtheta']
    n_directions = int(data['n_directions'])

    plotter = fixed_module2.ShapeDrawer_2D()

    # Draw the original feasible region
    plotter.plot_polygon(x_org=boundary_points, facecolor='blue',
                         xlim=xlim, ylim=ylim, label='Original region')

    # draw moderate model
    plotter.plot_polygon(A=A_moderate, b=b_moderate,
                         facecolor='yellow', xlim=xlim, ylim=ylim, label='Learned region-moderate')

    # draw feasible model
    plotter.plot_polygon(A=A_feasible, b=b_feasible,
                         facecolor='red', xlim=xlim, ylim=ylim, label='Learned region-feasible')

    # save
    save_name = f'{n_directions}_dtheta_{dtheta[0]:.2e}_{dtheta[len(dtheta)//2]:.2e}'
    plotter.save(os.path.join(output_dir, save_name), format='png')
    print(f"The feasible region comparison chart has been saved to: {output_dir}")


# =============================================================================
# Error distribution plot
# =============================================================================

def plot_boxplot(ax, data, labels, colors, title, ylabel):
    """Draw a boxplot with scatter points"""
    bp = ax.boxplot(data, tick_labels=labels, patch_artist=True)

    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color)

    for i, d in enumerate(data):
        x = np.random.normal(i + 1, 0.04, size=len(d))
        ax.scatter(x, d, alpha=0.5, s=10, color=colors[i],
                   edgecolors='black', linewidths=0.5)

    ax.set_ylabel(ylabel, fontsize=12)
    ax.set_title(title, fontsize=14)
    ax.grid(True, alpha=0.3)


def plot_error_distribution(data_path, output_dir):
    """Read error analysis data and draw box plots"""
    data = np.load(data_path)

    moderate_feas = data['moderate_feas']
    moderate_opt = data['moderate_opt']
    feasible_feas = data['feasible_feas']
    feasible_opt = data['feasible_opt']

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    labels = ['Learned region-moderate', 'Learned region-feasible']
    colors = ['lightblue', 'lightcoral']

    # Left: feasibility error
    plot_boxplot(axes[0], [moderate_feas, feasible_feas], labels, colors,
                 'Feasibility Errors', 'Feasibility Error')

    # Right: Optimality error
    plot_boxplot(axes[1], [moderate_opt, feasible_opt], labels, colors,
                 'Optimality Errors', 'Optimality Error')

    plt.tight_layout()
    save_path = os.path.join(output_dir, 'combined_error_distribution.svg')
    plt.savefig(save_path, dpi=300, bbox_inches='tight', format='svg')
    print(f"The combined error distribution plot has been saved to: {save_path}")
    plt.close()


# =============================================================================
# main program
# =============================================================================

if __name__ == '__main__':
    # Definition case dictionary
    dscases = {
        # 'case10ba_ds': TD_case.case10ba_ds(),
        # 'case17me_ds': TD_case.case17me_ds(),
         'case33bw_ds': TD_case.case33bw_ds(),
        # 'case51ga_ds': TD_case.case51ga_ds(),
        # 'case74_ds': TD_case.case74_ds(),
        # 'case118zh_ds': TD_case.case118zh_ds(),
        # 'case136ma_ds': TD_case.case136ma_ds(),
        # 'case533mt_hi_ds': TD_case.case533mt_hi_ds(),
        # 'case36real_3phase_ds': DS_case_3phase.case36real_3phase_ds(),
    }
    for casename, ppc in dscases.items():
        is_3phase = '3phase' in casename
        if is_3phase:
            result_dir = f'{PROJECT_ROOT}\\results\\ds_proj_paper\\{casename}\\A(36,2)_type3(8, 11)_lr1(3e-4)_lr2(1e-4)_rate(1e-4)'
        else:
            result_dir = (f'{PROJECT_ROOT}\\results\\ds_proj_paper\\{casename}\\'
                         'A(8,2)_type3(2,29)_lr1(3e-5)_lr2(1e-5)_rate(1e-4)')
        output_dir = f'{result_dir}\\figures\\comparison\\feasible\\contrast\\'

        # Read and draw feasible region comparison graph
        feasible_data_path = os.path.join(output_dir, 'feasible_region_data.npz')
        if os.path.exists(feasible_data_path):
            plot_feasible_region(feasible_data_path, output_dir)
        else:
            print(f"Feasible region data file not found: {feasible_data_path}")
            print("Please run first Box_error.py Calculated data")

        # Read and plot the error distribution
        error_dist_dir = os.path.join(os.path.dirname(output_dir), 'error_distributions')
        error_data_path = os.path.join(error_dist_dir, 'error_analysis_data.npz')
        if os.path.exists(error_data_path):
            plot_error_distribution(error_data_path, error_dist_dir)
        else:
            print(f"Error analysis data file not found: {error_data_path}")
            print("Please run first Box_error.py Calculated data")
